<?php return array (
  'site_title' => 'Finounce',
  'base_color' => '#635bff',
  'secondary_color' => '#ffaf30',
  'time_zone' => 'Africa/Douala',
  'force_ssl' => '0',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'base_currency_rate' => 1.0,
  'theme' => 'peerToPeer',
  'fraction_number' => 0,
  'paginate' => 20,
  'tradeCharge' => 5,
  'trade_extra_time' => 10,
  'incompleteLimit' => 5,
  'ad_rate_update' => 1,
  'email_verification' => 0,
  'email_notification' => 1,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'push_notification' => 1,
  'error_log' => 1,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'maintenance' => 0,
  'is_active_cron_notification' => 0,
  'bonus_amount' => '20',
  'joining_bonus' => 1,
  'sender_email' => 'support@mail.com',
  'sender_email_name' => 'Whapple Pay',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'sandbox.smtp.mailtrap.io',
    'smtp_port' => '2525',
    'smtp_encryption' => 'tls',
    'smtp_username' => '4336265ea7f60d',
    'smtp_password' => 'd0ff6c5dbfbe01',
  ),
  'fiat_currency_api' => '36fbb3371745a95658426245035598db',
  'fiat_currency_status' => 1,
  'crypto_currency_api' => '726ffba5-8523-4071-92d4-1775dbc481c4',
  'crypto_currency_status' => 1,
);