<?php
$arr = [
    "Home",
    "About",
    "Services",
    "Blog",
    "FAQ",
    "Contact",
    "Plan",
    "Login",
    "Logout",
    "Sign up",
    "Copyright",
    "All Rights Reserved",
    "Username",
    "Email Or Username",
    "Password",
    "Remember Me",
    "Forgot password?",
    "Don't have any account? Sign Up",
    "SIGN UP FORM",
    "Sponsor By",
    "First Name",
    "Last Name",
    "Email Address",
    "Your Phone Number",
    "Confirm Password",
    "Already have an account? Login",
    "Please confirm your password before continuing.",
    "Forgot Your Password?",
    "Already have an account?",
    "Reset Password",
    "Enter your Email Address",
    "Don't have an account?",
    "Send Password Reset Link",
    "New Password",
    "403 Forbidden",
    "You don’t have permission to access ‘/’ on this server.",
    "Back To Home",
    "Sorry page was not found!",
    "We're sorry, the page you requested could not be found. Please go back to the homepage or contact us at",
    "Method not allowed",
    "opps!",
    "Session has expired",
    "Dashboard",
    "Invest History",
    "Add Fund",
    "Fund History",
    "Transaction",
    "Payout",
    "Payout History",
    "My Referral",
    "Referral Bonus",
    "Profile Settings",
    "Support Ticket",
    "Main Balance",
    "Interest Balance",
    "Total Deposit",
    "Total Earn",
    "Account Statistics",
    "Total Invest",
    "Total Payout",
    "Total Ticket",
    "Total Referral Bonus",
    "Latest Registered Partner",
    "The last Referral Bonus",
    "Email",
    "Phone Number",
    "Joined At",
    "Code",
    "Pay Now",
    "Payment By",
    "Two Factor Authenticator",
    "Enable Two Factor Authenticator",
    "Disable Two Factor Authenticator",
    "Google Authenticator",
    "DOWNLOAD APP",
    "Verify Your OTP",
    "Close",
    "Verify",
    "Verify Your OTP to Disable",
    "Transactions",
    "Search for Transaction ID",
    "Remark",
    "Search",
    "SL No.",
    "Transaction ID",
    "Amount",
    "Remarks",
    "Time",
    "Type Here",
    "All Payment",
    "Complete Payment",
    "Pending Payment",
    "Cancel Payment",
    "Gateway",
    "Charge",
    "Search Service",
    "Subject",
    "Image Upload",
    "Upload",
    "Last Reply",
    "Reply",
    "Open",
    "Answered",
    "Customer Reply",
    "Closed",
    "Upload File",
    "Confirm",
    "Are you want to close ticket?",
    "My Profile",
    "Open Ticket",
    "Show Ticket",
    "No Data found",
    "Email Verification",
    "Update User",
    "Update Password",
    "Admin Feedback",
    "PAYOUT NOW",
    "Transaction Limit:",
    "Payout By",
    "Remove",
    "Confirm Now",
    "Return Interest",
    "Received Amount",
    "Upcoming Payment",
    "Search User",
    "Bonus From",
    "Current Password",
    "Address",
    "Submit",
    "Useful Links",
    "Deposit Balance",
    "2FA Security",
    "Referral Link",
    "subscribe now",
    "Buy",
    "Sell",
    "Blogs",
    "Sign In",
    "Clear all",
    "You have no notifications",
    "Dashboard",
    "My wallet",
    "Advertisements",
    "Buy Currency",
    "Sell Currency",
    "Trade List",
    "Running",
    "Complete",
    "Deposit History",
    "Payout History",
    "Support Tickets",
    "Edit Profile",
    "logout",
    "Profile",
    "Change Password",
    "Sign Out",
    "Add New",
    "New Advertisement",
    "I Want To",
    "What kind of advertisement do you wish to create? If you wish to sell bitcoins make sure you have bitcoins in your wallet.",
    "Select One",
    "Cryptocurrency",
    "Which cryptocurrency do you wish to buy or sell?",
    "Payment Method",
    "Which payment method will be used to pay the fiat currency?",
    "Currency",
    "Which fiat currency needs exchange from cryptocurrency?",
    "Price Type",
    "Margin",
    "Payment Window",
    "For Buyer: Within how many minutes do you promise to initiate the payment. For Seller: Within how many minutes you want to get paid",
    "Minimum Limit",
    "Minimum transaction limit in one trade.",
    "Maximum Limit",
    "Maximum transaction limit in one trade.",
    "Price Equation:",
    "Payment Details",
    "Terms of Trade",
    "Update Advertisement",
    "Update",
    "Currency Code",
    "Select Type",
    "Select Status",
    "Select",
    "Search",
    "New Ad",
    "SL No.",
    "Type",
    "Currency",
    "Margin / Fixed",
    "Payment Method",
    "Rate",
    "Payment Window",
    "Published",
    "Action",
    "Feedback",
    "Edit",
    "Enable",
    "Disable",
    "No data found",
    "Username or Email",
    "Select Crypto",
    "Crypto Currency",
    "Fiat Currency",
    "Select Fiat",
    "Select Method",
    "Offer Location",
    "Select Location",
    "Seller",
    "New Trade Request",
    "Rate:",
    "Payment Method:",
    "User:",
    "Trade Limits:",
    "Payment Window:",
    "How much you wish to buy?",
    "I will pay",
    "And Receive",
    "Write your contact message and other info for the trade here",
    "Send trade request",
    "Email Address Verified",
    "Mobile Number Verified",
    "Identity Verified",
    "Address Verified",
    "Terms of this trade",
    "Payment details fo this trade",
    "Trx Number",
    "Date",
    "Trx Number",
    "Amount",
    "Charge",
    "Transactions",
    "Admin Feedback",
    "Close",
    "Profile Settings",
    "Basic Info",
    "First Name",
    "verified",
    "Unverified",
    "Country:",
    "Joined:",
    "Email:",
    "Phone:",
    "Complete Trades:",
    "Advertisements:",
    "Avg Speed:",
    "Minutes",
    "Latest 10 Buy Ads",
    "Latest 10 Sell Ads",
    "Buyer",
    "How much you wish to sell?",
    "Email Address Verified",
    "Mobile Number Verified",
    "Identity Verified",
    "Address Verified",
    "Message",
    "Enter Message",
    "Upload File",
    "Submit",
    "Create Ticket",
    "Last Reply",
    "Open",
    "Answered",
    "Replied",
    "Closed",
    "Type Here",
    "Confirmation",
    "Are you want to close ticket?",
    "Exchange Rate:",
    "Cancelled",
    "Buyer Paid",
    "Completed",
    "Reported",
    "Please pay",
    "will be added to your wallet after confirmation about the payment.",
    "Once the buyer has confirmed your payment then",
    "This trade is Reported by",
    "Please wait for the system response.",
    "You can dispute this trade after",
    "Cancel",
    "I have paid",
    "Dispute",
    "release",
    "The buyer can dispute this trade anytime from now.",
    "trade information",
    "Buyer Name:",
    "Seller Name:",
    "Instructions to be followed",
    "terms of trade",
    "payment details",
    "Dispute Confirmation",
    "Are you sure that you have release this trade?",
    "Yes",
    "Release Confirmation",
    "Are you sure that you have release this trade?",
    "Cancel Confirmation",
    "Are you sure to cancel this trade?",
    "Paid Confirmation",
    "Are you sure that you have paid the amount?",
    "Trade Number",
    "With",
    "Type",
    "Currency",
    "Crypto Amount",
    "Requested On",
    "Wallet Address",
    "Withdraw Amount",
    "Request Withdraw",
    "Generate New XRP Address",
    "Username or Email",
    "Add",
    "Feedbacks on This Advertisement",
    "Add Feedback",
    "No feedback yet!",
    "Writing your own feedback may help others to continue trading",
    "Your message",
    "Opinion",
    "Given By",
    "Given At",
    "Details",
    "Feedback",
    "message",
    "Advertisement",
    "Total Trades",
    "Running Trades",
    "Complete Trades",
    "Do not miss any single important notification! Allow your browser to get instant push notification",
    "Please allow your browser to get instant push notification. Allow it from notification setting.",
    "Allow me",
    "Company Settings",
    "Settings",
    "Password Setting",
    "Push Notify Setting",
    "Notification List",
    "Save Changes",
    "This is push notification setting where you can manage your notification action click to continue.",
    "This is identity verification setting where you can verified your identity click to continue.",
    "This is password setting where you can change password click to continue.",
];
return $arr;
